name: CICD pipeline for debit card
on:
  push:
    branches:
      - master
    
      # workflow_dispatch: 
#   workflow_call:
#     inputs:
#       environment: 
#         type: String
#         required: true
#         description: provide the nev details
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      env:
        VERSION: 1.0.0
      run: |
        cd project_code
        mvn clean install
        cd target
        ls


